<a href="https://colab.research.google.com/github/ervaishnavisutar-del/ddaex/blob/main/Dirty_Employee_Ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("dirty-employee.csv")

In [3]:
df.head()

,Employee_ID,Full_Name,Age,Gender,Joining_Date,Department,Salary,Country,Phone,Marks,Unnamed: 10
0,101,Akif Attar,25.0,M,12-02-26,IT,"?25,000",India,9876543210,85,NaN
1,102,Ali Khan,30.0,Male,20-Mar-25,Information Technology,"?30,000",-9876543120,9876543211,90,NaN
2,103,Sara Sheikh,NaN,Female,12-05-20,I.T.,"?28,500",INDIA,(987)6543212,88,NaN
3,104,Ahmed Patel,-5.0,male,15-Jan-24,HR,"?35,000",ind,987-654-3213,92,NaN
4,105,Fatima Noor,180.0,F,10-08-23,Finance,"?40,000",Bharat,+91 9876543214,95,NaN

In [7]:
print("Shape:",df.shape)

Shape: (20, 11)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Employee_ID   20 non-null     int64
 1   Full_Name     19 non-null     object
 2   Age           17 non-null     float64
 3   Gender        20 non-null     object
 4   Joining_Date  18 non-null     object
 5   Department    20 non-null     object
 6   Salary        20 non-null     object
 7   Country       20 non-null     object
 8   Phone         19 non-null     object
 9   Marks         19 non-null     object
 10  Unnamed: 10   1 non-null      float64
dtypes: float64(2), int64(1), object(8)
memory usage: 1.8+ KB

In [10]:
df=df.drop_duplicates()

In [11]:
df.isnull().sum()

Employee_ID      0
Full_Name        1
Age              3
Gender           0
Joining_Date     2
Department       0
Salary           0
Country          0
Phone            1
Marks            1
Unnamed: 10     19
dtype: int64

In [13]:
df.drop(columns=['Unnamed: 10'],inplace=True)

In [15]:
df['Full_Name'].fillna('Unknown',inplace=True)

/tmp/ipykernel_2824/3225475273.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Full_Name'].fillna('Unknown',inplace=True)

In [16]:
df['Age'].describe()

count     17.000000
mean      91.235294
std      237.061577
min       -5.000000
25%       25.000000
50%       27.000000
75%       30.000000
max      999.000000
Name: Age, dtype: float64

In [20]:
df['Joining_Date']=pd.to_datetime(df['Joining_Date'],errors='coerce')

/tmp/ipykernel_2824/3010750481.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Joining_Date']=pd.to_datetime(df['Joining_Date'],errors='coerce')

In [22]:
df['Joining_Date']=df['Joining_Date'].dt.strftime("%Y-%m-%d")

In [23]:
df['Salary']=df['Salary'].replace('$','')

In [25]:
df['Salary']=df['Salary'].replace(',','')

In [26]:
df['Gender']=df['Gender'].replace({
    "M":"Male",
    "F":"Female",
    "male":"Male",
    "female":"Female"
})

In [27]:
df['Country']=df['Country'].str.title()

In [ ]:
df['Phone']=df['Phone'].str.replace(r'[^0-9]',regex=True)

In [29]:
df[(df['Age'])>=1&(df['Age']<=100)]

,Employee_ID,Full_Name,Age,Gender,Joining_Date,Department,Salary,Country,Phone,Marks
0,101,Akif Attar,25.0,Male,2026-12-02,IT,"?25,000",India,9876543210,85
1,102,Ali Khan,30.0,Male,2025-03-20,Information Technology,"?30,000",-9876543120,9876543211,90
4,105,Fatima Noor,180.0,Female,2023-10-08,Finance,"?40,000",Bharat,+91 9876543214,95
5,106,Unknown,27.0,Female,NaN,HR,"?27,000",India,9876543215,80
6,107,John Smith,29.0,Male,2022-12-31,IT,?,India,9876543216,1000
7,108,Priya Sharma,26.0,Female,2024-06-15,Finance,"?26,000",India,NaN,78
8,109,Rahul Verma,31.0,Male,2023-06-10,IT,"?31,000",India,9876543218,82
9,110,Ayesha Khan,28.0,Female,2025-01-11,I.T.,"?29,500",India,9876543219,86
10,111,Ali Khan,30.0,Male,2025-03-20,Information Technology,"?30,000",-9876543120,9876543211,90
12,113,Imran Sheikh,24.0,Male,2022-08-07,I.T.,"?22,000",Ind,9876543221,75
13,114,Neha Patil,27.0,Female,NaN,2024,?ance,"₹27,500",India,+91 9876543222
14,115,Karan Joshi,29.0,m,2021-11-30,Information Technology,"?32,000",Bharat,9876543223,84
15,116,Meera Desai,26.0,Female,2020-09-15,IT,"?26,500",India,9876543224,81
17,118,Sneha Kulkarni,23.0,Female,2022-08-20,Finance,"?23,000",India,9876543226,79
18,119,Vikram Singh,999.0,Male,2024-10-01,I.T.,"?50,000",India,9876543227,91
19,120,Nida Shaikh,22.0,Female,NaN,Information Technology,"?21,500",Ind,9876543228,77

In [32]:
df.to_csv('dirty-employee_cleaned.csv',index=False)